server:
  port: 8071
spring:
  application:
    name: "config"
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/vkondrav/spring-boot.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths: "spring-microservices/config/src/main/resources/config/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

