  discovery.docker "micro_scrape" {
    host             = "unix:///var/run/docker.sock"
    refresh_interval = "5s"
  }
    
  discovery.relabel "micro_scrape" {
    targets = []
    
    rule {
    source_labels = ["__meta_docker_container_name"]
    regex         = "/(.*)"
    target_label  = "container"
    }
  }
    
  loki.source.docker "micro_scrape" {
    host             = "unix:///var/run/docker.sock"
    targets          = discovery.docker.micro_scrape.targets
    forward_to       = [loki.write.default.receiver]
    relabel_rules    = discovery.relabel.micro_scrape.rules
    refresh_interval = "5s"
  }
    
  loki.write "default" {
    endpoint {
    url       = "http://gateway:3100/loki/api/v1/push"
    tenant_id = "tenant1"
    }
    external_labels = {}
  }