apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: alloy
  name: alloy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alloy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: alloy
    spec:
      containers:
        - args:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/var/lib/alloy/data
            - /etc/alloy/config.alloy
          image: grafana/alloy:latest
          name: alloy
          ports:
            - containerPort: 12345
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/alloy/config.alloy
              name: alloy-cm0
              readOnly: true
              subPath: config.alloy
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: alloy-config.yaml
                path: config.alloy
            name: alloy-cm0
          name: alloy-cm0
