apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - args:
            - -config.file=/etc/loki/config.yaml
            - -target=backend
            - -legacy-read-mode=false
          image: grafana/loki:3.1.0
          name: loki-backend
          ports:
            - containerPort: 3100
              protocol: TCP
            - containerPort: 7946
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/loki/config.yaml
              name: backend-cm0
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: loki-config.yaml
                path: config.yaml
            name: backend-cm0
          name: backend-cm0
