apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: cards
  name: cards
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cards
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: cards
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8070/eureka/
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/app/libs/opentelemetry-javaagent-2.9.0.jar
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo:4317
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_SERVICE_NAME
              value: cards
            - name: SPRING_APPLICATION_NAME
              value: cards
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config:8071/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://cardsdb:3307/cardsdb
            - name: SPRING_PROFILES_ACTIVE
              value: default
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
          image: vkondrav/cards:v1
#          livenessProbe:
#            exec:
#              command:
#                - curl --fail --silent http://localhost:9000/actuator/health | grep UP || exit 1
#            failureThreshold: 10
#            initialDelaySeconds: 10
#            periodSeconds: 10
#            timeoutSeconds: 5
          name: cards-service
          ports:
            - containerPort: 9000
              protocol: TCP
      restartPolicy: Always
