apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - command:
            - sh
            - -euc
            - |
              /run.sh
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          image: grafana/grafana:latest
          livenessProbe:
            exec:
              command:
                - wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data
            - mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              name: grafana-cm1
              subPath: datasource.yml
      restartPolicy: Always
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
        - configMap:
            items:
              - key: datasource.yml
                path: datasource.yml
            name: grafana-cm1
          name: grafana-cm1
