apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: hookdeck
  name: hookdeck
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hookdeck
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: hookdeck
    spec:
      containers:
        - args:
            - |
              bin/hookdeck login
              bin/hookdeck listen http://host.docker.internal:8071 github-spring
          command:
            - /bin/sh
            - -c
          image: hookdeck/hookdeck-cli
          name: hookdeck
          volumeMounts:
            - mountPath: /root/.config/hookdeck
              name: hookdeck-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: hookdeck-cm0
          name: hookdeck-cm0
