apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: loansdb
  name: loansdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loansdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: loansdb
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: loansdb
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_TCP_PORT
              value: "3308"
            - name: MYSQL_USER
              value: user
          image: mysql:8.0
#          livenessProbe:
#            exec:
#              command:
#                - mysqladmin ping -h localhost
#            failureThreshold: 10
#            initialDelaySeconds: 5
#            periodSeconds: 10
#            timeoutSeconds: 5
          name: loansdb
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: loansdb-data
      restartPolicy: Always
      volumes:
        - name: loansdb-data
          persistentVolumeClaim:
            claimName: loansdb-data
