apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval:     5s # Set the scrape interval to every 5 seconds.
      evaluation_interval: 5s # Evaluate rules every 5 seconds.

    scrape_configs:
      - job_name: 'accounts'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'accounts:8081' ]
      - job_name: 'loans'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'loans:8090' ]
      - job_name: 'cards'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'cards:9000' ]
      - job_name: 'edge'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'edge:8072' ]
      - job_name: 'eureka'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'eureka:8070' ]
      - job_name: 'config'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'config:8071' ]
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
