apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: tempo
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tempo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: tempo
    spec:
      containers:
        - args:
            - -config.file
            - /etc/tempo-config.yml
          image: grafana/tempo:2.6.1
          name: tempo
          ports:
            - containerPort: 3100
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/tempo-config.yml
              name: tempo-cm0
              subPath: tempo-config.yml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: tempo.yml
                path: tempo-config.yml
            name: tempo-cm0
          name: tempo-cm0
