server:
  port: 8081
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: user
    password: password
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"