services:

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  config:
    image: vkondrav/config:v1
    container_name: config_service
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"

  hookdeck:
    image: hookdeck/hookdeck-cli
    container_name: hookdeck
    networks:
      - backend
    entrypoint: [ "/bin/sh","-c" ]
    command:
    - |
      bin/hookdeck login
      bin/hookdeck listen http://host.docker.internal:8071 github-spring
    depends_on:
      - config
    volumes:
      - ~/.config/hookdeck:/root/.config/hookdeck

  eureka:
    image: vkondrav/eureka:v1
    container_name: eureka_service
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - backend
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config:8071/"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_APPLICATION_NAME: "eureka"
      SPRING_RABBITMQ_HOST: "rabbitmq"
    depends_on:
      config:
        condition: service_healthy

  accounts:
    image: vkondrav/accounts:v1
    container_name: accounts_service
    ports:
      - "8081:8081"
    healthcheck:
      test: "curl --fail --silent http://localhost:8081/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - backend
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config:8071/"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8070/eureka/"
    depends_on:
      config:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
      eureka:
        condition: service_healthy

  accountsdb:
    image: mysql:8.0
    container_name: accountsdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - accountsdb_data:/var/lib/mysql

  cards:
    image: vkondrav/cards:v1
    container_name: cards_service
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent http://localhost:9000/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - backend
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config:8071/"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_APPLICATION_NAME: "cards"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3307/cardsdb"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8070/eureka/"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy

  cardsdb:
    image: mysql:8.0
    container_name: cardsdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cardsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3306"
    networks:
      - backend
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - cardsdb_data:/var/lib/mysql

  loans:
    image: vkondrav/loans:v1
    container_name: loans_service
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent http://localhost:8090/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - backend
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config:8071/"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_APPLICATION_NAME: "loans"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3308/loansdb"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8070/eureka/"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy

  loansdb:
    image: mysql:8.0
    container_name: loansdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loansdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3306"
    networks:
      - backend
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - loansdb_data:/var/lib/mysql

networks:
  backend:
    driver: "bridge"

volumes:
  accountsdb_data:
  cardsdb_data:
  loansdb_data: